<?php
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2011 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$vardefs = array (
  'fields' => 
  array (
    'incident_date_time' => 
    array (
      'required' => true,
      'name' => 'incident_date_time',
      'vname' => 'LBL_INCIDENT_DATE_TIME',
      'type' => 'datetimecombo',
      'massupdate' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'size' => '20',
      'dbType' => 'datetime',
    ),
    'incident_report_date_time' => 
    array (
      'required' => true,
      'name' => 'incident_report_date_time',
      'vname' => 'LBL_INCIDENT_REPORT_DATE_TIME',
      'type' => 'datetimecombo',
      'massupdate' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'size' => '20',
      'dbType' => 'datetime',
    ),
    'inc_staff_reporter_id' => 
    array (
      'required' => false,
      'name' => 'inc_staff_reporter_id',
      'vname' => 'LBL_INC_STAFF_REPORTER_ID',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => 'ID of staff person reporting incident',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '36',
      'size' => '20',
    ),
    'inc_staff_supervisor_id' => 
    array (
      'required' => false,
      'name' => 'inc_staff_supervisor_id',
      'vname' => 'LBL_INC_STAFF_SUPERVISOR_ID',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => 'ID of supervisor of staff person reporting incident',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '36',
      'size' => '20',
    ),
    'inc_recip_is_participant' => 
    array (
      'required' => false,
      'name' => 'inc_recip_is_participant',
      'vname' => 'LBL_INC_RECIP_IS_PARTICIPANT',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => 'Recipient of incident is participant',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '36',
      'size' => '20',
    ),
    'inc_recip_is_du' => 
    array (
      'required' => false,
      'name' => 'inc_recip_is_du',
      'vname' => 'LBL_INC_RECIP_IS_DU',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => 'Recipient of incident is dwelling unit',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '36',
      'size' => '20',
    ),
    'inc_recip_is_staff' => 
    array (
      'required' => false,
      'name' => 'inc_recip_is_staff',
      'vname' => 'LBL_INC_RECIP_IS_STAFF',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => 'Recipient of incident is staff person',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '36',
      'size' => '20',
    ),
    'inc_recip_is_family' => 
    array (
      'required' => false,
      'name' => 'inc_recip_is_family',
      'vname' => 'LBL_INC_RECIP_IS_FAMILY',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => 'Recipient of incident is family member',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '36',
      'size' => '20',
    ),
    'inc_recip_is_acquaintance' => 
    array (
      'required' => false,
      'name' => 'inc_recip_is_acquaintance',
      'vname' => 'LBL_INC_RECIP_IS_ACQUAINTANCE',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => 'Recipient of incident is acquaintance',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '36',
      'size' => '20',
    ),
    'inc_contact_person' => 
    array (
      'required' => false,
      'name' => 'inc_contact_person',
      'vname' => 'LBL_INC_CONTACT_PERSON',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => 'ID of contact person if contact person is a participant and participant is recipient of incident',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '36',
      'size' => '20',
    ),
    'inctype' => 
    array (
      'required' => false,
      'name' => 'inctype',
      'vname' => 'LBL_INCTYPE',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '_4',
      'comments' => '',
      'help' => '&quot;1 - Suspected privacy or data loss  2 - Serious incident  3 - Observed/reported risk  4 - Suspected falsification of data  5 - Failure to obtain legally effective consent -5 - Other&quot;',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'INCIDENT_TYPE_CL1',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'inctype_oth' => 
    array (
      'required' => false,
      'name' => 'inctype_oth',
      'vname' => 'LBL_INCTYPE_OTH',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => 'Other type of incident',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'incloss_cmptr_model' => 
    array (
      'required' => false,
      'name' => 'incloss_cmptr_model',
      'vname' => 'LBL_INCLOSS_CMPTR_MODEL',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => 'Privacy loss - computer model',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '16',
      'size' => '20',
    ),
    'incloss_cmptr_sn' => 
    array (
      'required' => false,
      'name' => 'incloss_cmptr_sn',
      'vname' => 'LBL_INCLOSS_CMPTR_SN',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => 'Privacy loss - computer serial number',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '32',
      'size' => '20',
    ),
    'incloss_cmptr_decal' => 
    array (
      'required' => false,
      'name' => 'incloss_cmptr_decal',
      'vname' => 'LBL_INCLOSS_CMPTR_DECAL',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => 'Privacy loss - computer decal number',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '32',
      'size' => '20',
    ),
    'incloss_rem_media' => 
    array (
      'required' => false,
      'name' => 'incloss_rem_media',
      'vname' => 'LBL_INCLOSS_REM_MEDIA',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => 'Privacy loss - removable media',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '32',
      'size' => '20',
    ),
    'incloss_paper' => 
    array (
      'required' => false,
      'name' => 'incloss_paper',
      'vname' => 'LBL_INCLOSS_PAPER',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => 'Privacy loss - paper documents',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '32',
      'size' => '20',
    ),
    'incloss_oth' => 
    array (
      'required' => false,
      'name' => 'incloss_oth',
      'vname' => 'LBL_INCLOSS_OTH',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => 'Suspected privacy loss is other',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '250',
      'size' => '20',
    ),
    'inc_reported' => 
    array (
      'required' => false,
      'name' => 'inc_reported',
      'vname' => 'LBL_INC_REPORTED',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '_6',
      'comments' => '',
      'help' => 'Incident reported to local IRB',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'CONFIRM_TYPE_CL3',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'inc_description' => 
    array (
      'required' => false,
      'name' => 'inc_description',
      'vname' => 'LBL_INC_DESCRIPTION',
      'type' => 'text',
      'massupdate' => 0,
      'comments' => '',
      'help' => 'Incident Description',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '20',
    ),
    'inc_action' => 
    array (
      'required' => false,
      'name' => 'inc_action',
      'vname' => 'LBL_INC_ACTION',
      'type' => 'text',
      'massupdate' => 0,
      'comments' => '',
      'help' => 'Corrective action taken',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '20',
    ),
    'inc_recip_is_other' => 
    array (
      'required' => false,
      'name' => 'inc_recip_is_other',
      'vname' => 'LBL_INC_RECIP_IS_OTHER',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '6',
      'comments' => '',
      'help' => '6 - Other                                  -7 - Not Applicable',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'NSC_OTHER_NA',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'name' => 
    array (
      'name' => 'name',
      'vname' => 'LBL_NAME',
      'type' => 'name',
      'dbType' => 'varchar',
      'len' => '36',
      'unified_search' => true,
      'required' => true,
      'importable' => 'required',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'size' => '20',
    ),
  ),
  'relationships' => 
  array (
  ),
);
?>
