<?php
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2010 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/
$vardefs = array (
  'fields' => 
  array (
    'psu_id' => 
    array (
      'required' => false,
      'name' => 'psu_id',
      'vname' => 'LBL_PSU_ID',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '20000014',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'psu_id_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'tsu_id' => 
    array (
      'required' => false,
      'name' => 'tsu_id',
      'vname' => 'LBL_TSU_ID',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '36',
      'size' => '20',
    ),
    'outreach_event_id' => 
    array (
      'required' => false,
      'name' => 'outreach_event_id',
      'vname' => 'LBL_OUTREACH_EVENT_ID',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '36',
      'size' => '20',
    ),
    'outreach_event_date' => 
    array (
      'required' => false,
      'name' => 'outreach_event_date',
      'vname' => 'LBL_OUTREACH_EVENT_DATE',
      'type' => 'date',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'size' => '20',
    ),
    'outreach_target' => 
    array (
      'required' => false,
      'name' => 'outreach_target',
      'vname' => 'LBL_OUTREACH_TARGET',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'outreach_target_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'outreach_target_oth' => 
    array (
      'required' => false,
      'name' => 'outreach_target_oth',
      'vname' => 'LBL_OUTREACH_TARGET_OTH',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'outreach_mode' => 
    array (
      'required' => false,
      'name' => 'outreach_mode',
      'vname' => 'LBL_OUTREACH_MODE',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'outreach_mode_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'outreach_mode_oth' => 
    array (
      'required' => false,
      'name' => 'outreach_mode_oth',
      'vname' => 'LBL_OUTREACH_MODE_OTH',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'outreach_type' => 
    array (
      'required' => false,
      'name' => 'outreach_type',
      'vname' => 'LBL_OUTREACH_TYPE',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'outreach_type_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'outreach_type_oth' => 
    array (
      'required' => false,
      'name' => 'outreach_type_oth',
      'vname' => 'LBL_OUTREACH_TYPE_OTH',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'outreach_tailored' => 
    array (
      'required' => false,
      'name' => 'outreach_tailored',
      'vname' => 'LBL_OUTREACH_TAILORED',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'outreach_tailored_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'outreach_lang1' => 
    array (
      'required' => false,
      'name' => 'outreach_lang1',
      'vname' => 'LBL_OUTREACH_LANG1',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'outreach_lang1_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'outreach_lang2' => 
    array (
      'required' => false,
      'name' => 'outreach_lang2',
      'vname' => 'LBL_OUTREACH_LANG2',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'contact_lang_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'outreach_lang_oth' => 
    array (
      'required' => false,
      'name' => 'outreach_lang_oth',
      'vname' => 'LBL_OUTREACH_LANG_OTH',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'outreach_race1' => 
    array (
      'required' => false,
      'name' => 'outreach_race1',
      'vname' => 'LBL_OUTREACH_RACE1',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'outreach_race1_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'outreach_race2' => 
    array (
      'required' => false,
      'name' => 'outreach_race2',
      'vname' => 'LBL_OUTREACH_RACE2',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'STAFF_RACE_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'outreach_race_oth' => 
    array (
      'required' => false,
      'name' => 'outreach_race_oth',
      'vname' => 'LBL_OUTREACH_RACE_OTH',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'outreach_culture1' => 
    array (
      'required' => false,
      'name' => 'outreach_culture1',
      'vname' => 'LBL_OUTREACH_CULTURE1',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'outreach_culture1_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'outreach_culture2' => 
    array (
      'required' => false,
      'name' => 'outreach_culture2',
      'vname' => 'LBL_OUTREACH_CULTURE2',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'outreach_culture2_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'outreach_culture_oth' => 
    array (
      'required' => false,
      'name' => 'outreach_culture_oth',
      'vname' => 'LBL_OUTREACH_CULTURE_OTH',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'outreach_quantity' => 
    array (
      'required' => false,
      'name' => 'outreach_quantity',
      'vname' => 'LBL_OUTREACH_QUANTITY',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'outreach_cost' => 
    array (
      'required' => false,
      'name' => 'outreach_cost',
      'vname' => 'LBL_OUTREACH_COST',
      'type' => 'decimal',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '10',
      'size' => '20',
      'precision' => '2',
    ),
    'outreach_staffing' => 
    array (
      'required' => false,
      'name' => 'outreach_staffing',
      'vname' => 'LBL_OUTREACH_STAFFING',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'outreach_incident' => 
    array (
      'required' => false,
      'name' => 'outreach_incident',
      'vname' => 'LBL_OUTREACH_INCIDENT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'OUTREACH_INCIDENT_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'incident_id' => 
    array (
      'required' => false,
      'name' => 'incident_id',
      'vname' => 'LBL_INCIDENT_ID',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'len' => '36',
      'size' => '20',
    ),
  ),
  'relationships' => 
  array (
  ),
);
?>
